In [1]:
#in numpy loops are slow for computing it is better to use other ways like :-
#1.vectorization 


In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
#using the loop for printing the squares 
result = []
for _ in arr:
    result.append(_**2)
result

[np.int64(1),
 np.int64(4),
 np.int64(9),
 np.int64(16),
 np.int64(25),
 np.int64(36),
 np.int64(49)]

In [7]:
#using the numpy vectorization method which is more efficient 
result_numpy = arr**2
result_numpy

array([ 1,  4,  9, 16, 25, 36, 49])

In [8]:
#see how numpy make it so simple and it is more efficeint and fast also 

In [9]:
#it is fast because it is using the simd - simple instruction and multiple data 

In [10]:
#broadcasting means it is simple .. it is like is broadcasting everywhere 
#like reult is 10,12,2,3,4,5
#if we will do the broadcasting of this as result +10 it will apply to all the value of the reusl 

In [12]:
#example 
numbers = np.array([1,2,34,5,5,55,66,])
numbers 

array([ 1,  2, 34,  5,  5, 55, 66])

In [14]:
#broadcasting 
numbers+10#it will simple add the 10 to the result of the numbers 

array([11, 12, 44, 15, 15, 65, 76])

In [21]:
#this is the broadcasting with 2D arrays ,it work on rows to rows of the arrays 

arr1  = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([-arr1[:]])#it include all the value of the arr1 but in the neagative form 

arr2

array([[[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]]])

In [22]:
arr1+arr2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [23]:
#normalizing the data using the broadcasting 

In [24]:
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
data

array([[10, 20, 30],
       [15, 25, 35],
       [20, 30, 40],
       [25, 35, 45],
       [30, 40, 50]])

In [27]:
mean = data.mean(axis  = 0)
mean

array([20., 30., 40.])

In [28]:
std = data.std(axis = 0)
std

array([7.07106781, 7.07106781, 7.07106781])

In [29]:
data - mean/std

array([[ 7.17157288, 15.75735931, 24.34314575],
       [12.17157288, 20.75735931, 29.34314575],
       [17.17157288, 25.75735931, 34.34314575],
       [22.17157288, 30.75735931, 39.34314575],
       [27.17157288, 35.75735931, 44.34314575]])