In [1]:
#in this file we will understand the builtin mathmatics computation in numpy

In [2]:
import numpy as np 

In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,11])

In [43]:
int(np.mean(arr))#mean is nothing just a stastistics method of finding the average

5

In [44]:
np.std(arr)#std is nothing but another statistics method of finding if std is near the mean or far from the mean if it is near the mean then it is called low std and if it too low or too high that mean then it is called high std

np.float64(3.0397368307141326)

In [45]:
np.min(arr)#for finding the minimum value of the array 

np.int64(1)

In [46]:
int(np.max(arr))#for finding the maximum value of the array

11

In [47]:
np.var(arr)#variance is also a method used for data differences it is the method of the statistics  

np.float64(9.239999999999998)

In [48]:
np.prod(arr)#it is method to get the product of the full array 

np.int64(3991680)

In [49]:
np.sum(arr)#it is the method to get the sum of the full array

np.int64(56)

In [50]:
np.median(arr)#calculate the median of the data it  is also stats method 

np.float64(5.5)

In [51]:
np.percentile(arr,10)

np.float64(1.9)

In [52]:
int(np.argmin(arr))#argmin is the method that is used to get to know the min value of the array it basically tell the index where your min value is  in the data|

0

In [53]:
int(np.argmax(arr))#basically tell the index of the maximum value in the given array

9

In [54]:
np.unique(arr)#np.unique is basically a function in which it will provid ewith the a aray whcih has uniquye values and oesn't not contain the duplicate value 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [55]:
arr2 = np.array([1,2,3,4,5,6,7,7,8,9])
arr2

array([1, 2, 3, 4, 5, 6, 7, 7, 8, 9])

In [56]:
np.corrcoef(arr,arr2)#it is coefficeint correaltion of the two arrays using the matrix

array([[1.        , 0.98879136],
       [0.98879136, 1.        ]])

In [58]:
np.diff(arr)#it is basically a fucntion where you get an array but it is subratected the number of previous value 

array([1, 1, 1, 1, 1, 1, 1, 1, 2])

In [59]:
np.cumsum(arr)#it is basically adding the values after each other 

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 56])

In [66]:
np.linspace(0,5,2)#it just give the number ofvalues in between the range which is given by the array

array([0., 5.])

In [68]:
np.log(arr)#it just give the log of the valuees of the given the array it is a concept of mathmatics 

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.39789527])

In [70]:
np.exp(arr)#it is the exponential of the contatant 2.78 something it exponent the as like if there is value 10 in the array then exp will give the value of the 2.788 somthing liek this it is the expl contant so it give powe r to the 10 basically multipying the 10 times 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 5.98741417e+04])