In [1]:
#in this file we will learn numpy arrays 

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])#creaing the numpy array
arr


array([1, 2, 3, 4, 5, 6])

In [4]:
np.zeros((1,4))#

array([[0., 0., 0., 0.]])

In [5]:
np.zeros((3,4))#methods of creating arrays from the scratch this one if for zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,4))#this one for 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((30,6),-100239348903)#this is for any value including one and 0 also -+

array([[-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903, -100239348903, -100239348903,
        -100239348903, -100239348903],
       [-100239348903, -100239348903,

In [8]:
np.eye(4)#this si the method for the matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(0,100,10)#this is the arange in  which it gives us the number like 0,no,0+no in it will only 
#give the value till no-1 this is the rule 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.linspace(0,1,5)#this is the linspace method of the numpy which provide space in between the value 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
myarr = np.array([1,2,3,4,5,6,7],dtype='float64')#method to change the same data type like changing the same variable 
myarr

array([1., 2., 3., 4., 5., 6., 7.])

In [12]:
myarr.shape#for checking the size of the array  

(7,)

In [13]:
myarr.size#for checking the size of the array

7

In [14]:
myarr.ndim#for checking the dimension of the array

1

In [15]:
myarr.dtype

dtype('float64')

In [16]:
myarr_int = myarr.astype('int64')#this is the method used for changing the data type but from different variable but using the same data type
myarr_int

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
myarr_int.dtype

dtype('int64')

In [18]:
myarr_float = myarr_int.astype('float64')
myarr_float

array([1., 2., 3., 4., 5., 6., 7.])

In [20]:
array9 = np.array([[1,2,3,4],[4,5,6,4],[7,8,9,10]])
array9
array9.shape

(3, 4)

In [22]:
reshaped = array9.reshape((4,3))
reshaped

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  4,  7],
       [ 8,  9, 10]])

In [26]:
reshaped.flatten()#used to change the 2D --> to 1D


array([ 1,  2,  3,  4,  4,  5,  6,  4,  7,  8,  9, 10])