In [28]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[:,1] = 0
arr
arr[:,0:3]=100000
arr

array([[100000, 100000, 100000],
       [100000, 100000, 100000],
       [100000, 100000, 100000]])

In [29]:
arr

array([[100000, 100000, 100000],
       [100000, 100000, 100000],
       [100000, 100000, 100000]])

In [30]:
np.sum(arr,axis=1)#axis 0 corresponds to the rows and sum f

#of the logic 

array([300000, 300000, 300000])

In [31]:
 np.sum(arr,axis=0)

array([300000, 300000, 300000])

In [32]:
arr[0][2]

np.int64(100000)

In [33]:
arr[0,2]

np.int64(100000)

In [34]:
arr[0:1,1:3]

array([[100000, 100000]])

In [35]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],#this is the 3D array
[[7, 8, 9], [10, 11, 12]]])


In [36]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr3D[1,1,0]#THIS IS THE INDEXING FOR 3D ARRAYS 

np.int64(10)

In [38]:
arr3D.shape

(2, 2, 3)

In [39]:
arr3D[:0:]

array([], shape=(0, 2, 3), dtype=int64)

In [40]:
arr3D[:,1,:]#this is type of indexing where you can take both the sheets and all the value of that indxing you have putted

array([[ 4,  5,  6],
       [10, 11, 12]])