In [1]:
#in this file we will learn indexing and slicing in the python 

In [2]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
flat = arr.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
flat[1]

np.int64(2)

In [7]:
flat[0]

np.int64(1)

In [9]:
flat[8]

np.int64(9)

In [10]:
flat[1:4]

array([2, 3, 4])

In [11]:
flat[0:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
flat[0:0]

array([], dtype=int64)

In [13]:
flat[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
flat[-1:]

array([9])

In [15]:
flat[-2:]

array([8, 9])

In [16]:
flat[-3:]

array([7, 8, 9])

In [17]:
flat[5:]

array([6, 7, 8, 9])

In [18]:
flat[6:]

array([7, 8, 9])

In [19]:
flat[::2]

array([1, 3, 5, 7, 9])

In [20]:
falt[::3]

NameError: name 'falt' is not defined

In [21]:
flat[::3]

array([1, 4, 7])

In [22]:
flat[::4]

array([1, 5, 9])

In [23]:
flat[::5]

array([1, 6])

In [24]:
flat[::6]

array([1, 7])

In [25]:
flat[::7]

array([1, 8])

In [26]:
b = flat
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = 200
b

200

In [28]:
b = flat

In [29]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = flat[-1:]-1
b

array([8])

In [31]:
b

array([8])

In [32]:
b+1

array([9])

In [33]:
b+2

array([10])

In [34]:
b+3

array([11])

In [42]:
flat

array([44444,     2,     3,     4,     5,     6,     7,     8,     9])

In [47]:
b = flat.copy()
b

array([44444,     2,     3,     4,     5,     6,     7,     8,     9])

In [48]:
b[0] = 4444444455

In [49]:
b

array([4444444455,          2,          3,          4,          5,
                6,          7,          8,          9])

In [50]:
flat#slicing is not the copy it is just the point of way 
#in python it is created from the copy but this case is different in the numpy it does not create the copy but
#uses the memory to change the original one too this is why numpy is different than python
#that is why it is said that it is original thing you are sharing 

array([44444,     2,     3,     4,     5,     6,     7,     8,     9])

In [51]:
flat

array([44444,     2,     3,     4,     5,     6,     7,     8,     9])

In [52]:
#copy in slicing is the method that is  used in numpy to copy it so the original one will not change

In [53]:
flat

array([44444,     2,     3,     4,     5,     6,     7,     8,     9])

In [56]:
arr2 = np.array([1,3,4,5,6,7,8,9,12,13,14,15])

In [57]:
arr2

array([ 1,  3,  4,  5,  6,  7,  8,  9, 12, 13, 14, 15])

In [66]:
arr2[[2,4,5]]#we have to use the list to call the funtion if we will not do that it will show the error 

array([4, 6, 7])