In [1]:
import numpy as np 
arr1 = np.array([1,2,3,4,56,4])
arr1


array([ 1,  2,  3,  4, 56,  4])

In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr1.shape

(6,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2.shape

(3, 3)

In [6]:
type(arr2)

numpy.ndarray

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr4 = np.array(["mony","doni","43"],dtype="object")
arr4

array(['mony', 'doni', '43'], dtype=object)

In [9]:
arr5 = np.array([10, 20, 30, 40, 50])
arr5.shape

(5,)

In [10]:
type(arr5)

numpy.ndarray

In [11]:
arr5[0]

np.int64(10)

In [12]:
arr5[1]

np.int64(20)

In [13]:
arr5[-1]

np.int64(50)

In [14]:
arr5[0:2]

array([10, 20])

In [15]:
arr5[2:]

array([30, 40, 50])

In [16]:
arr5[1:4]

array([20, 30, 40])

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr[2]= 100

In [18]:
arr

array([  1,   2, 100,   4,   5])

In [19]:
arr_new = arr*3

In [20]:
arr_new

array([  3,   6, 300,  12,  15])

In [21]:
arr_bool = arr
# arr_bool[:] = 0

In [22]:
arr_bool

array([  1,   2, 100,   4,   5])

In [23]:
marks = np.array([45, 67, 89, 34, 90, 55])
marks 


array([45, 67, 89, 34, 90, 55])

In [24]:
new = marks>60
marks[new]

array([67, 89, 90])

In [25]:
passed = marks>40
passed = marks[passed]
passed

array([45, 67, 89, 90, 55])

In [26]:
marks

array([45, 67, 89, 34, 90, 55])

In [27]:
passed.size

5

In [28]:
#marks below the 40 
low = marks<40
low_marks = marks[low]
low_marks[0] = 0
low_marks 

array([0])

In [31]:
 lowest_marks = int(np.argmin(marks))

In [33]:
f"student with lowest marks is with marks = {lowest_marks}"

'student with lowest marks is with marks = 3'

In [2]:
import numpy as np 
arr = np.array ([1,2,3,4,5,6,7,8])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr.mean()

np.float64(4.5)

In [6]:
arr.sum()

np.int64(36)

In [7]:
arr.min()

np.int64(1)

In [9]:
arr.max()

np.int64(8)

In [10]:
arr.argmax()

np.int64(7)

In [11]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
arr.sum()

np.int64(210)

In [13]:
arr.sum(axis = 1)

array([ 60, 150])

In [14]:
arr.sum(axis=0)

array([50, 70, 90])

In [15]:
marks = np.array([45, 67, 89, 34, 90])
marks.mean()

np.float64(65.0)

In [16]:
marks.std()

np.float64(22.653917983430592)

In [17]:
#by seeing the std we can understood that data is very very spreaded highy

In [18]:
marks = np.array([[78, 85, 90],
                  [65, 70, 60],
                  [90, 92, 88],
                  [55, 60, 58]])


In [19]:
marks

array([[78, 85, 90],
       [65, 70, 60],
       [90, 92, 88],
       [55, 60, 58]])

In [20]:
marks.max()

np.int64(92)

In [21]:
marks.min()

np.int64(55)

In [23]:
marks.sum(axis = 1)

array([253, 195, 270, 173])

In [24]:
marks.mean(axis = 0)

array([72.  , 76.75, 74.  ])

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr.shape

(15,)

In [36]:
reshaped =arr.reshape(3,5)

In [38]:
reshaped.shape

(3, 5)

In [39]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [40]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])



In [48]:
marks = np.array([78, 85, 90, 65, 70, 60])
marks.reshape(2,3)

array([[78, 85, 90],
       [65, 70, 60]])

In [49]:
marks.flatten()

array([78, 85, 90, 65, 70, 60])

In [50]:
marks.T

array([78, 85, 90, 65, 70, 60])

In [51]:
arr = np.array([10, 20, 30])


In [52]:
arr

array([10, 20, 30])

In [53]:
arr+5

array([15, 25, 35])

In [54]:
arr-10

array([ 0, 10, 20])

In [55]:
arr*2

array([20, 40, 60])

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a

array([1, 2, 3])

In [57]:
b

array([4, 5, 6])

In [58]:
a+b

array([5, 7, 9])

In [59]:
a*b

array([ 4, 10, 18])

In [60]:
a**2

array([1, 4, 9])

In [62]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
arr*3

array([[ 30,  60,  90],
       [120, 150, 180]])

In [63]:
np.append(arr,10)

array([10, 20, 30, 40, 50, 60, 10])

In [64]:
arr*3

array([[ 30,  60,  90],
       [120, 150, 180]])

In [65]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

b = np.array([10, 20, 30])
arr+b

array([[11, 22, 33],
       [14, 25, 36]])

In [66]:
marks = np.array([[78, 85, 90],
                  [65, 70, 60],
                  [90, 92, 88]])
marks+5

array([[83, 90, 95],
       [70, 75, 65],
       [95, 97, 93]])

In [68]:
marks[0,0]+10

np.int64(88)

In [70]:
arr = np.array([10, 25, 40, 55, 70])
arr_new= arr<30
arr[arr_new]

array([10, 25])

In [71]:
arr = np.array([10, 25, 40, 55, 70])
arr_new = (arr>20)&(arr<60)

In [74]:
arr[arr_new]

array([25, 40, 55])

In [84]:
arr = np.array([10, 25, 40, 55, 70])
arr[arr>50] = 100

In [85]:
arr

array([ 10,  25,  40, 100, 100])

In [86]:
arr[arr<30] = 0

In [88]:
arr

array([  0,   0,  40, 100, 100])

In [89]:
arr = np.array([45, 67, 23, 89, 12] ,dtype = 'object')
arr[arr>50] = 'pass'
arr[arr<20] = 'fail'

TypeError: '<' not supported between instances of 'str' and 'int'