In [1]:
import numpy as np 
arr1 = np.array([1,2,3,4,56,4])
arr1


array([ 1,  2,  3,  4, 56,  4])

In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr1.shape

(6,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2.shape

(3, 3)

In [6]:
type(arr2)

numpy.ndarray

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr4 = np.array(["mony","doni","43"],dtype="object")
arr4

array(['mony', 'doni', '43'], dtype=object)

In [9]:
arr5 = np.array([10, 20, 30, 40, 50])
arr5.shape

(5,)

In [10]:
type(arr5)

numpy.ndarray

In [11]:
arr5[0]

np.int64(10)

In [12]:
arr5[1]

np.int64(20)

In [13]:
arr5[-1]

np.int64(50)

In [14]:
arr5[0:2]

array([10, 20])

In [15]:
arr5[2:]

array([30, 40, 50])

In [16]:
arr5[1:4]

array([20, 30, 40])

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr[2]= 100

In [18]:
arr

array([  1,   2, 100,   4,   5])

In [19]:
arr_new = arr*3

In [20]:
arr_new

array([  3,   6, 300,  12,  15])

In [21]:
arr_bool = arr
# arr_bool[:] = 0

In [22]:
arr_bool

array([  1,   2, 100,   4,   5])

In [23]:
marks = np.array([45, 67, 89, 34, 90, 55])
marks 


array([45, 67, 89, 34, 90, 55])

In [24]:
new = marks>60
marks[new]

array([67, 89, 90])

In [25]:
passed = marks>40
passed = marks[passed]
passed

array([45, 67, 89, 90, 55])

In [26]:
marks

array([45, 67, 89, 34, 90, 55])

In [27]:
passed.size

5

In [28]:
#marks below the 40 
low = marks<40
low_marks = marks[low]
low_marks[0] = 0
low_marks 

array([0])

In [31]:
 lowest_marks = int(np.argmin(marks))

In [33]:
f"student with lowest marks is with marks = {lowest_marks}"

'student with lowest marks is with marks = 3'